services:

  db:
    image: mysql:8.0.22
    container_name: mysql_eam
    restart: always
    hostname: db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - eam_apps

  app:
    image: dvdma12/hospital-api:latest
    container_name: hospital_api_app
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}
    ports:
      - "${SPRING_APP_PORT}:4500"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eam_apps

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eam_apps

networks:
  eam_apps:
    driver: bridge

volumes:
  mysql_data:
    name: mysql_eam_data
