version: '3.8'

services:
  db:
    build:
      context: ./MYSQL
      dockerfile: Dockerfile
    container_name: mysql_eam
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    hostname: apps_database
    networks:
      - eam_apps
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer_wms
    restart: always
    ports:
      - 8000:8080
    networks:
      - eam_apps

networks:
  eam_apps:
    driver: bridge

volumes:
  mysql_data:
